# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ignore:
      - goarch: 386
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    flags: -buildmode=exe
    ignore:
      - goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
